twig:
    default_path: '%kernel.project_dir%/src'
    paths:
        # BackOffice
        'src/Backoffice/DashboardBundle/Templates': 'AdminDashboard'
        'src/Backoffice/ThemeBundle/Templates': 'BoTheme'
        'src/Backoffice/SettingsBundle/Templates': 'SettingsBundleTheme'
        'src/Backoffice/SecurityBundle/Templates': 'SecurityBundleTheme'
        'src/Backoffice/CommonBundle/Templates': 'CommonBundleTheme'
        'src/Backoffice/UserBundle/Templates': 'UserBundleTheme'
        'src/Backoffice/ProductsBundle/Templates': 'BoProductsBundle'
        


        # Front
        'src/Front/ThemeBundle/Templates': 'FrontThemeBundle'
when@test:
    twig:
        strict_variables: true
