controllers:
    resource: ../src/
    type: attribute

BackofficeUserBundle:
    resource: ../src/Backoffice/UserBundle/Config/routing.yaml

BackofficeSettingsBundle:
    resource: ../src/Backoffice/SettingsBundle/Config/routing.yaml

BackofficeCommonBundle:
    resource: ../src/Backoffice/CommonBundle/Config/routing.yaml

BackofficeProductsBundle:
    resource: ../src/Backoffice/ProductsBundle/Config/routing.yaml

    
